# Best Model
The best model we determined is gradient boosting on the data set that has been categorised. (Without PCA)
The hyperparameters for the gradient boosting is:
1. Learning Rate = 0.1
2. n estimator = 1000

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.ensemble import GradientBoostingRegressor

In [2]:
best_model = GradientBoostingRegressor(learning_rate=0.1, n_estimators=1000, random_state = 8)

In [3]:
train_X =pd.read_csv('train_X_cat.csv',index_col = 0)
original_test = pd.read_csv('test_X_num.csv',index_col = 0)
train_y_logsales =pd.read_csv('train_y_logsales.csv',index_col = 0)
train_y_logsales = train_y_logsales.sales

#Call in the test data provided
test_X =pd.read_csv('test_X_cat.csv',index_col = 0)

#training of best model:
best_model.fit(train_X,train_y_logsales)

#Prediction for ground truth:
result = pd.DataFrame(original_test)
Logsales_prediction = best_model.predict(test_X)
result['sales'] = np.exp(best_model.predict(test_X))

In [4]:
# finding the critical fractile for the residual distribution
price = 20
cost = 12
salvage = 8
Overage_cost = cost - salvage
Underage_cost = price - cost
critical_fractile = Underage_cost/(Overage_cost + Underage_cost)

# Best Inventory Decision

Following the exponential distribution for residual

In [5]:
# This is the inventory decision for each day
demand_values_exp = round(-(result['sales'])*np.log(1-critical_fractile))
result['inventory'] = demand_values_exp

In [6]:
result.head()

,productID,brandID,attribute1,attribute2,attribute3,attribute4,clickVolume,avgOriginalUnitPrice,avgFinalUnitPrice,ma14SalesVolume,...,meanAge,gender,meanEducation,maritalStatus,plus,meanPurchasePower,meanUserLevel,meanCityLevel,sales,inventory
0,77,38,3.0,100.0,2,5.670374,173.0,180.835683,165.459988,12.857143,...,26.960521,0.053158,2.958528,0.668194,0.148227,2.347953,2.638135,1.997034,4.847924,5.0
1,47,30,4.0,100.0,9,5.191429,142.0,190.802856,138.995392,2.285714,...,33.111475,0.317086,3.292282,0.709143,0.272464,2.409795,3.973464,1.385002,5.440971,6.0
2,33,25,3.0,100.0,1,2.461109,144.0,127.385574,123.286542,4.500000,...,30.353550,0.000000,2.668048,1.002511,0.000000,1.955541,2.937542,2.369596,1.548753,2.0
3,68,28,3.0,100.0,2,4.659192,220.0,240.873276,168.258175,17.500000,...,29.692379,0.000000,2.470400,0.424764,0.000000,1.932938,2.480643,2.505191,1.941870,2.0
4,65,16,3.0,90.0,2,15.554293,4079.0,85.013188,68.521885,115.785714,...,33.128355,0.201974,2.432218,0.592206,0.005535,2.428117,1.792081,2.669685,137.397631,151.0

In [7]:
result.to_csv('group1.csv')